apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-src-image
  spec:
    params:
    - name: url
      value: docker.io/yellocabins/or-nodejs-express-stack
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-dest-image
  spec:
    params:
    - name: url
      value: docker.io/yellocabins/or-nodejs-express-stack-dest
    type: image
kind: List
