apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: package-release-update-pl-push-binding
  namespace: tekton-pipelines
  author: Oscar I. Ricaud
  date: 04/21/20
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: docker-tag
      value: '$(body.repository.name):$(body.head_commit.id)'
    - name: event-type
      value: $(header.X-Github-Event)
    - name: event-ref
      value: $(body.ref)
    - name: webhooks-tekton-git-branch
      value: $(body.webhooks-tekton-git-branch)