apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-sonar-scan-build-deploy-pl
  namespace: kabanero
spec:
  params:
    - description: The event type
      name: event-type
      type: string
    - description: The event ref
      name: event-ref
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: validate-stack-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
      taskRef:
        kind: Task
        name: nodejs-validate-stack-task
    - name: scan-build-push-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
          - name: git-source
            resource: git-source
      runAfter:
        - validate-stack-task
      taskRef:
        kind: Task
        name: nodejs-sonar-scan-build-push-task
    - name: image-scan-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      runAfter:
        - scan-build-push-task
      taskRef:
        kind: Task
        name: nodejs-image-scan-task
    - conditions:
        - conditionRef: nodejs-deployment-condition
          params:
            - name: event-type
              value: $(params.event-type)
            - name: event-ref
              value: $(params.event-ref)
      name: deploy-task
      resources:
        inputs:
          - from:
              - scan-build-push-task
            name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      runAfter:
        - image-scan-task
      taskRef:
        kind: Task
        name: nodejs-deploy-task